name = "cuisine-wheel-sg"
compatibility_date = "2026-02-01"
main = "dist/worker.js"

[assets]
directory = "./dist/public"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
DATABASE_URL = "libsql://cuisine-wheel-chrisrothwell.aws-ap-northeast-1.turso.io"

[observability]
[observability.logs]
enabled = true
invocation_logs = true